### PR TITLE
fix:  Pinned configurations not working

### LINKED ISSUE #278: Pinning code to an execution target does not seem to be working
As I navigate between files that have been pinned with different targets, the last set target is always on and not what was pinned.

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes  #278

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

File: src/hpccplatform/launchConfig.ts [hunk 1]
```diff
@@ -71,13 +71,12 @@ export function launchConfigurations(refresh = false): string[] {
             gatherServers();
         }
     }
-    const retVal = Object.keys(g_launchConfigurations);
+    const retVal = Object.values(g_launchConfigurations);
     if (retVal.length === 0) {
```
Comment (dehilsterlexis) [inline src/hpccplatform/launchConfig.ts:75]: @GordonSmith, I'm not sure it can ever get here. If there are no launch configurations, you block it already. Maybe there is a cases where this would get here if zero. Doesn't hurt I guess.

**Review by dehilsterlexis — APPROVED** [review]
Looks good. One minor point that may be moot.

File: src/hpccplatform/launchConfig.ts (hunk 1 above)
Comment (GordonSmith) [reply src/hpccplatform/launchConfig.ts:75]: I think it can still have 0 entries at this point...
